todolist/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from updating_list import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name = "index"),
    url(r'^user_info/', include('user_info.urls')),
    url(r'^updating_list/', include('updating_list.urls')),
]

updating_list/urls.py
from django.conf.urls import url
from updating_list import views

app_name = "updating_list"

# urls down below

urlpatterns = [
    url(r'^todo_list/$', views.todo_list, name="todo_list"),
    url(r'^contact/$', views.contact, name="contact"),
    url(r'^about/$', views.about, name="about")
]

user_info/urls.py
from django.conf.urls import url
from user_info import views

app_name = "user_info"

# urls for user_info down below

urlpatterns = [
    url(r'^login/$', views.login, name="login"),
    url(r'^registration/$', views.registration, name="registration")
]

updating_list/models.py
from django.db import models

# Create your models here.

user_info/models.py
from django.db import models

# Create your models here.

updating_list/views.py
from django.shortcuts import render

# Create your views for updating_list here.


def index(request):
    return render(request, 'index.html')

def todo_list(request):
    return render(request, 'updating_list/todo_list.html')

def contact(request):
    return render(request, 'updating_list/contact_me.html')

def about(request):
    return render(request, 'updating_list/about_me.html')

user_info/views.py
from django.shortcuts import render

# Create your views for user_info here.

def login(request):
    return render(request, 'user_info/login.html')

def registration(request):
    return render(request, 'user_info/registration.html')

templates/base.html
<!DOCTYPE html>

<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Base</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href='https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' rel='stylesheet'>

</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">

            <a class="navbar-brand" href="{% url 'index' %}">TL</a>
            <button class="navbar-toggler " type="button " data-toggle="collapse " data-target="#navbarNav " aria-controls="navbarNav " aria-expanded="false " aria-label="Toggle navigation ">
          <span class="navbar-toggler-icon "></span>
        </button>
            <div class="collapse navbar-collapse " id="navbarNav ">
                <ul class="navbar-nav ">
                    <li class="nav-item ">
                        <a class="nav-link " href="{% url 'updating_list:todo_list' %}">My TodoList</a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link " href="{% url 'updating_list:about' %}">About Me</a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link " href="{% url 'updating_list:contact' %}">Contact Me</a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link " href="{% url 'user_info:login' %}">Login</a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link " href="{% url 'user_info:registration' %}">Registration</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        {% block body_block %}
        <!-- Anything outseide of this will be inherited if you call base -->
        {% endblock %}
    </div>

    <script src="" async defer></script>
</body>

</html>

templates/index.html
<!DOCTYPE html> {% extends 'base.html' %} {% block body_block %}
<title>Home Page</title>
<h1>This is my Index Page</h1>
<h1>Test</h1>
{% endblock %}

templates/updating_list/about_me.html
<!DOCTYPE html> {% extends 'base.html' %} {% block body_block %}

<title>About Me</title>

<div class="container">
    <h1>This is About Me page</h1>
</div>
{% endblock %}

templates/updating_list/contact_me.html
<!DOCTYPE html> {% extends 'base.html' %} {% block body_block %}

<title>Contact Me</title>
<h1>This is Contact me page</h1>
{% endblock %}

templates/updating_list/todo_list.html
<!DOCTYPE html> {% extends 'base.html' %} {% block body_block %}{% load static %}
<title>ToDo List</title>

<link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.0.3/css/font-awesome.css' rel='stylesheet'>
<script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>
<script type='text/javascript' src='https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js'></script>
<script type='text/javascript' src='hhttps://stackpath.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js'></script>
<link rel="stylesheet" href="{% static 'style/style.css' %}">

<div class="container ">
    <div class="page-content page-container " id="page-content ">
        <div class="padding ">
            <div class="row container d-flex justify-content-center ">
                <div class="col-md-12 ">
                    <div class="card px-3 ">
                        <div class="card-body ">
                            <h4 class="card-title ">Owais's Todo list</h4>
                            <div class="add-items d-flex "> <input type="text " class="form-control todo-list-input " placeholder="What do you need to do today? "> <button class="add btn btn-primary font-weight-bold todo-list-add-btn ">Add</button> </div>
                            <div class="list-wrapper ">
                                <ul class="d-flex flex-column-reverse todo-list ">
                                    <li>
                                        <div class="form-check "> <label class="form-check-label "> <input class="checkbox " type="checkbox "> For what reason would it be advisable. <i class="input-helper "></i></label> </div> <i class="remove mdi mdi-close-circle-outline "></i>
                                    </li>
                                    <li class="completed ">
                                        <div class="form-check "> <label class="form-check-label "> <input class="checkbox " type="checkbox " checked=" "> For what reason would it be advisable for me to think. <i class="input-helper"></i></label> </div> <i class="remove mdi mdi-close-circle-outline "></i>
                                    </li>
                                    <li>
                                        <div class="form-check "> <label class="form-check-label "> <input class="checkbox " type="checkbox "> it be advisable for me to think about business content? <i class="input-helper"></i></label> </div> <i class="remove mdi mdi-close-circle-outline "></i>
                                    </li>
                                    <li>
                                        <div class="form-check "> <label class="form-check-label "> <input class="checkbox " type="checkbox "> Print Statements all <i class="input-helper "></i></label> </div> <i class="remove mdi mdi-close-circle-outline "></i>
                                    </li>
                                    <li class="completed ">
                                        <div class="form-check "> <label class="form-check-label "> <input class="checkbox " type="checkbox " checked=" "> Call Rampbo <i class="input-helper "></i></label> </div> <i class="remove mdi mdi-close-circle-outline "></i>
                                    </li>
                                    <li>
                                        <div class="form-check "> <label class="form-check-label "> <input class="checkbox " type="checkbox "> Print bills <i class="input-helper "></i></label> </div> <i class="remove mdi mdi-close-circle-outline "></i>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'scripts/main.js' %} " async defer></script>


{% endblock %}

templates/user_info/login.html
<!DOCTYPE html> {% extends 'base.html' %} {% block body_block %}

<title>Login Page</title>
<h1>This is Login Page</h1>
{% endblock %}

templates/user_info/registration.html
<!DOCTYPE html> {% extends 'base.html' %} {% block body_block %}
<title>Registration</title>
<h1>This is Registration Page</h1>
{% endblock %}